// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Director struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Movie struct {
	ID     string    `json:"id"`
	Title  string    `json:"title"`
	URL    string    `json:"url"`
	Author *Director `json:"author"`
}

type NewMovie struct {
	Title      string `json:"title"`
	URL        string `json:"url"`
	DirectorID string `json:"directorId"`
}
